[2024-08-01T16:13:25.875+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-01T16:13:25.884+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-08-01T16:13:19.868612+00:00 [queued]>
[2024-08-01T16:13:25.887+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kezekte_etl.transform_data manual__2024-08-01T16:13:19.868612+00:00 [queued]>
[2024-08-01T16:13:25.887+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-01T16:13:25.892+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data> on 2024-08-01 16:13:19.868612+00:00
[2024-08-01T16:13:25.897+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-01T16:13:25.897+0000] {standard_task_runner.py:63} INFO - Started process 112 to run task
[2024-08-01T16:13:25.898+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kezekte_etl', 'transform_data', 'manual__2024-08-01T16:13:19.868612+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/kezekte_etl.py', '--cfg-path', '/tmp/tmpxfgh1d0r']
[2024-08-01T16:13:25.899+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask transform_data
[2024-08-01T16:13:25.931+0000] {task_command.py:426} INFO - Running <TaskInstance: kezekte_etl.transform_data manual__2024-08-01T16:13:19.868612+00:00 [running]> on host cd4398d9193e
[2024-08-01T16:13:25.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kezekte_etl' AIRFLOW_CTX_TASK_ID='transform_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-01T16:13:19.868612+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-01T16:13:19.868612+00:00'
[2024-08-01T16:13:25.969+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-01T16:13:25.984+0000] {base.py:84} INFO - Using connection ID 'postgresql_conn' for task execution.
[2024-08-01T16:13:25.987+0000] {sql.py:487} INFO - Running statement: 
            insert into raw_animals (chip_id, type, nickname, gender, breed, passport_number, register_date, birthday, status, ownership, 
                                    register_type, tagging_location, tagging_place, tagging_date, district_area, date_vaccination, date_sterilization_castration)
            values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            on conflict (passport_number) do nothing;
        , parameters: ('398010000259435', 'Собака', '9435', 'Самец', 'Беспородная', 'KZD310724-0189728', '01.08.2024 20:50:15', '14.12.2023', 'Активный', 'Безнадзорное', 'Мечение животного', 'Общественное объединение "Надежда плюс kst"', 'Реабилитационный центр для животных', '31.07.2024', 'Костанай г.а.', 'Не вакцинирован', 'Не стерилизован/кастрирован')
[2024-08-01T16:13:25.990+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-01T16:13:25.991+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kezekte_etl.py", line 76, in transform_data
    postgres_hook.run(insert_sql, parameters=(animal_id, animal_type, animal_nickname, animal_gender, animal_breed, animal_passport, animal_register, animal_birthday, anima_status, animal_ownership, animal_register_type, animal_tagging_location, animal_tagging_place, animal_tagging_date, animal_district_area, animal_date_vaccination, animal_date_sterilization_castration))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 490, in _run_command
    cur.execute(sql_statement, parameters)
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2024-08-01T16:13:26.001+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=kezekte_etl, task_id=transform_data, run_id=manual__2024-08-01T16:13:19.868612+00:00, execution_date=20240801T161319, start_date=20240801T161325, end_date=20240801T161326
[2024-08-01T16:13:26.006+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 121 for task transform_data (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 112)
[2024-08-01T16:13:26.036+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-01T16:13:26.043+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-01T16:13:26.043+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
